# Generated by Django 5.0.4 on 2024-11-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='budget',
            field=models.FloatField(default=0),
        ),
    ]
