# Generated by Django 5.0.4 on 2024-11-06 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customusermodel_budget'),
        ('invitations', '0003_remove_family_created_by_remove_family_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='invitations.family'),
        ),
    ]
