# Generated by Django 5.0.4 on 2024-11-15 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customusermodel_family'),
        ('invitations', '0004_family_created_by_family_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members_of_family', to='invitations.family'),
        ),
    ]
