# Generated by Django 5.0.4 on 2024-11-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingscalculator',
            name='potential_savings',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savingscalculator',
            name='suggested_savings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
