# Generated by Django 5.0.4 on 2024-10-08 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups_title', models.CharField(max_length=50)),
                ('category_tittle', models.CharField(max_length=50)),
                ('category_note', models.CharField(max_length=200)),
                ('assigned_amount', models.FloatField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
