# Generated by Django 5.0.4 on 2024-10-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_tittle', models.CharField(max_length=50)),
                ('category_note', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='groups',
            name='category_note',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='category_tittle',
        ),
    ]
