# Generated by Django 5.0.4 on 2024-10-08 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_category_remove_groups_category_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='assigned_amount',
        ),
        migrations.AddField(
            model_name='category',
            name='assigned_amount',
            field=models.FloatField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
