# Generated by Django 5.0.4 on 2024-10-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groups_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_tittle',
            new_name='category_title',
        ),
    ]
