# Generated by Django 5.0.4 on 2024-10-14 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_category_category_author_alter_groups_category'),
        ('invitations', '0002_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invitations.family'),
        ),
    ]
