# Generated by Django 5.0.4 on 2024-10-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_groups_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='category',
        ),
        migrations.AddField(
            model_name='groups',
            name='categories',
            field=models.ManyToManyField(related_name='groups', to='groups.category'),
        ),
    ]
