# Generated by Django 5.0.4 on 2024-11-08 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_category_category_type'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.bank'),
        ),
    ]
