# Generated by Django 5.0.4 on 2024-11-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_remove_groups_bank_category_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='assigned_amount',
            field=models.FloatField(default=0),
        ),
    ]
