# Generated by Django 5.1.2 on 2024-10-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_osoba_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Kobieta'), (2, 'Mężczyzna'), (3, 'Inne')], null=True),
        ),
    ]
