# Generated by Django 5.1.2 on 2024-12-02 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_osoba_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='published_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
