# Generated by Django 5.1.2 on 2024-10-31 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_position_osoba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
