# Generated by Django 5.0.4 on 2024-11-27 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('goal_type', models.CharField(choices=[('vacation', 'Wakacje'), ('home_renovation', 'Remont'), ('emergency_fund', 'Fundusz awaryjny'), ('education', 'Edukacja'), ('other', 'Inne')], max_length=50)),
                ('target_amount', models.FloatField()),
                ('current_amount', models.FloatField(default=0)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
