# Generated by Django 5.0.4 on 2024-11-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='added_amount',
            field=models.FloatField(default=0),
        ),
    ]
