# Generated by Django 5.0.4 on 2024-11-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_expense_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='total_expenses',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='total_income',
            field=models.FloatField(default=0),
        ),
    ]
