# Generated by Django 5.0.4 on 2024-11-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_budget_total_expenses_budget_total_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='family',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='total_expenses',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='total_income',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
