# Generated by Django 5.0.4 on 2024-11-15 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_alter_family_created_by'),
        ('transactions', '0004_remove_income_family_remove_budget_total_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks_family', to='invitations.family'),
        ),
    ]
